server:
  port: 2080
  
  
image:
  path: D:/upload/
  
#mybatis  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.cete.springboot.entity          # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  http:
    multipart:
      enabled: true             #默认支持文件上传
      file-size-threshold: 0    #支持文件写入磁盘
      location: F:/upload/temp/ #上传文件的临时目录
      max-file-size: 5000Mb      #最大支持文件大小
      max-request-size: 5000Mb   #最大支持请求文件大小
      
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/file?useUnicode=true&characterEncoding=utf8               # 数据库名称
    username: mysql
    password: mysql
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
      
      
  mvc:
    view:
      prefix: /html/
      suffix: .html      